-- This script renames the `rank` column to `grade` in the ddr_16_user_song_records table,
-- since `rank` is a MySQL reserved keyword and we want to maintain compatibility for both.

ALTER TABLE `ddr_16_user_song_records` RENAME TO `ddr_16_user_song_records_orig`;

CREATE TABLE `ddr_16_user_song_records` (
  `id`	bigint NOT NULL,
  `option_appearance`	varchar ( 255 ),
  `area`	integer,
  `option_arrow_color`	varchar ( 255 ),
  `option_arrow_skin`	varchar ( 255 ),
  `bemani_flag`	integer,
  `boo_count`	integer,
  `option_boost`	varchar ( 255 ),
  `bpm_max`	integer,
  `bpm_min`	integer,
  `calories`	integer,
  `clear_kind`	integer,
  `option_cut`	varchar ( 255 ),
  `end_time`	datetime,
  `ex_score`	integer,
  `fast_count`	integer,
  `folder`	integer,
  `option_freeze_arrow`	varchar ( 255 ),
  `genre_flag`	integer,
  `good_count`	integer,
  `gr_air`	integer,
  `gr_chaos`	integer,
  `gr_freeze`	integer,
  `gr_stream`	integer,
  `gr_voltage`	integer,
  `great_count`	integer,
  `option_guidelines`	varchar ( 255 ),
  `is_ea_pass`	boolean,
  `is_game_over`	boolean,
  `is_premium`	boolean,
  `is_repeater`	boolean,
  `is_takeover`	boolean,
  `option_judegement_layer`	varchar ( 255 ),
  `option_jumps`	varchar ( 255 ),
  `level`	integer,
  `life`	integer,
  `option_life_gauge`	varchar ( 255 ),
  `limited`	integer,
  `location_id`	varchar ( 255 ),
  `machine_pcbid`	varchar ( 255 ),
  `marvelous_count`	integer,
  `max_combo`	integer,
  `miss_count`	integer,
  `ng_count`	integer,
  `note_type`	integer,
  `ok_count`	integer,
  `perfect_count`	integer,
  `play_side`	integer,
  `play_style`	integer,
  `grade`	integer,
  `region`	integer,
  `score`	integer,
  `option_screen_filter`	varchar ( 255 ),
  `option_scroll`	varchar ( 255 ),
  `series`	integer,
  `share`	boolean,
  `shop_area`	varchar ( 255 ),
  `shop_name`	varchar ( 255 ),
  `option_fast_slow_count`	boolean,
  `slow_count`	integer,
  `song_artist`	varchar ( 255 ),
  `song_base_name`	varchar ( 255 ),
  `song_id`	integer,
  `song_title`	varchar ( 255 ),
  `option_speed`	varchar ( 255 ),
  `stage_num`	integer,
  `option_step_zone`	varchar ( 255 ),
  `option_turn`	varchar ( 255 ),
  `weight_100`	integer,
  `ghost_data_id`	bigint,
  `user_id`	bigint,
  PRIMARY KEY(`id`)
);

INSERT INTO ddr_16_user_song_records(id, option_appearance, area, option_arrow_color, option_arrow_skin, bemani_flag, boo_count, option_boost, bpm_max, bpm_min, calories, clear_kind, option_cut, end_time, ex_score, fast_count, folder, option_freeze_arrow, genre_flag, good_count, gr_air, gr_chaos, gr_freeze, gr_stream, gr_voltage, great_count, option_guidelines, is_ea_pass, is_game_over, is_premium, is_repeater, is_takeover, option_judegement_layer, option_jumps, level, life, option_life_gauge, limited, location_id, machine_pcbid, marvelous_count, max_combo, miss_count, ng_count, note_type, ok_count, perfect_count, play_side, play_style, grade, region, score, option_screen_filter, option_scroll, series, share, shop_area, shop_name, option_fast_slow_count, slow_count, song_artist, song_base_name, song_id, song_title, option_speed, stage_num, option_step_zone, option_turn, weight_100, ghost_data_id, user_id) SELECT id, option_appearance, area, option_arrow_color, option_arrow_skin, bemani_flag, boo_count, option_boost, bpm_max, bpm_min, calories, clear_kind, option_cut, end_time, ex_score, fast_count, folder, option_freeze_arrow, genre_flag, good_count, gr_air, gr_chaos, gr_freeze, gr_stream, gr_voltage, great_count, option_guidelines, is_ea_pass, is_game_over, is_premium, is_repeater, is_takeover, option_judegement_layer, option_jumps, level, life, option_life_gauge, limited, location_id, machine_pcbid, marvelous_count, max_combo, miss_count, ng_count, note_type, ok_count, perfect_count, play_side, play_style, rank, region, score, option_screen_filter, option_scroll, series, share, shop_area, shop_name, option_fast_slow_count, slow_count, song_artist, song_base_name, song_id, song_title, option_speed, stage_num, option_step_zone, option_turn, weight_100, ghost_data_id, user_id FROM ddr_16_user_song_records_orig;

DROP TABLE ddr_16_user_song_records_orig;